### ISSUE TITLE
can not download the checkpoint

### ISSUE THREAD

**Issue by JoshonSmith** [Shivanshu-Gupta/gist-icl#1]
can not open the website: https://bbbe-128-195-10-172.ngrok-free.app/gistlms/

**Comment by Shivanshu-Gupta** [comment]
Sorry about the late reply. I was hospitalized for the past few months. The models are now online at http://nlp.ics.uci.edu/gist-icl/gistlms/. The links in the readme have been updated. Let me know if you face anymore trouble.
