### ISSUE TITLE
ckpt link does not work.

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [Shivanshu-Gupta/gist-icl#2]
Hi Authors,

The ckpt link does not work (link to nothing);

Thanks for your attention.

**Comment by Shivanshu-Gupta** [comment]
Sorry about the late reply. I was hospitalized for the past few months. The models are now online at http://nlp.ics.uci.edu/gist-icl/gistlms/. The links in the readme have been updated. Let me know if you face anymore trouble.

**Comment by Zhaoyi-Li21** [comment]
Hi, Authors,

Thanks for sharing the checkpoints of the gist models. I found the pretrains.tar file (containing multiple models) is too large (108 GB) to download. Would you mind splitting it into individual files? For me, I need large-size trained on flan2022_zs_len256_max10K with 1 token.

Thanks for your attention!
