### ISSUE TITLE
pretrains.tar file (containing multiple models) is too large (108 GB) to download.

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [Shivanshu-Gupta/gist-icl#3]
Hi, Authors,

Thanks for sharing the checkpoints of the gist models. I found the pretrains.tar file (containing multiple models) is too large (108 GB) to download. Would you mind splitting it into individual files? For me, I need large-size trained on flan2022_zs_len256_max10K with 1 token.

Thanks for your attention!

**Comment by Shivanshu-Gupta** [comment]
Hi, have you tried downloading from the new URL (http://nlp.ics.uci.edu/gist-icl/gistlms/)? The ngrok download limit was causing issues previously. The URLs were updated in the readme a while back.

**Comment by Zhaoyi-Li21** [comment]
Hi, Thanks for the reply. Actually I tried this URL (https://nlp.ics.uci.edu/gist-icl/gistlms/) . The pretrains.tar file is around 108 GB which seems too large for me.

**Comment by Shivanshu-Gupta** [comment]
Okay, I have added new tar files for each of the pretrained models. [flan2022_zs_len256_max10K-1tok-flan-t5-large.tar.gz](https://nlp.ics.uci.edu/gist-icl/gistlms/pretrains/flan2022_zs_len256_max10K-1tok-flan-t5-large.tar.gz) is 5.5GB. Hope that's small enough.
